#+TITLE: emacs configuration
#+AUTHOR: Ian Kenney
#+PROPERTY: header-args :tangle init.el :results none

* User interface

#+begin_src elisp
(setq inhibit-startup-message t)
(setq ring-bell-function 'ignore)

(tool-bar-mode -1)
(scroll-bar-mode -1)
(menu-bar-mode -1)

(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode)

(add-hook 'prog-mode-hook (lambda () (setq show-trailing-whitespace t)))

(setq initial-frame-alist
      '((width . 100) (height . 45)))

(add-to-list 'default-frame-alist
             '(font . "Fira Code-12"))

(setq use-dialog-box nil)
#+end_src

#+begin_src elisp
(setq epa-pinentry-mode 'loopback)
(setq epa-keys-select-method 'minibuffer)
#+end_src

* Paths and executables

Explicitly include user level =bin= since it's not obvious how emacs
will be launched all the time.

#+begin_src elisp
(add-to-list 'exec-path "~/local/bin")
(add-to-list 'exec-path "~/.local/bin")
#+end_src

* Packages
** Custom packages

Custom single file packages are kept in the =lisp/= subdirectory.

#+begin_src elisp
(add-to-list 'load-path (locate-user-emacs-file "lisp/"))
#+end_src

#+begin_src elisp
(require 'pytest)
(require 'pythontooling)
#+end_src

** Repository setup

#+begin_src elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
#+end_src

** Package installation and configuration

#+begin_src elisp
(use-package company
  :config
  (global-company-mode t)
  :ensure t)

(use-package ledger-mode
  :ensure t
  :defer)

(use-package git-gutter
  :config
  (global-git-gutter-mode t)
  (global-git-gutter-mode +1)
  (global-set-key (kbd "M-g p") 'git-gutter:previous-hunk)
  (global-set-key (kbd "M-g n") 'git-gutter:next-hunk)
  :ensure t)

(use-package magit
  :ensure t
  :defer)

(use-package consult
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :ensure t
  :init
  (global-set-key (kbd "C-c g") 'consult-ripgrep))

(setq completion-styles '(basic substring partial-completion flex))

(use-package vertico
  :ensure t
  :init
  (vertico-mode))

(use-package org-roam
  :ensure t
  :custom
  (org-roam-directory "~/Documents/roam/")
  (org-roam-capture-templates
   '(("d" "default" plain "%?"
      :target (file+head "${slug}.org"
			 "#+title: ${title}\n")
      :unnarrowed t)
     ("e" "encrypted" plain "%?"
      :target (file+head "${slug}.org.gpg"
			 "#+title: ${title}\n")
      :unnarrowed t)))
  :bind (("C-c n l" . org-roam-buffer-toggle)
	 ("C-c n f" . org-roam-node-find)
	 ("C-c n i" . org-roam-node-insert))
  :config
  (org-roam-setup))

#+end_src

* Projects

#+begin_src elisp
(setq project-switch-commands '((project-find-file "Find file" "f")
                                (project-find-dir "Find dir" "d")
                                (project-dired "Dired" "D")
  				  (consult-grep "ripgrep" "g")
                                (magit-project-status "Magit" "m"))
      )
#+end_src

Disable save file prompt before compiling. While this is generally
useful it gets in my way more than it helps me. Most of the time I
have unrelated open files (such as org) that might be in incomplete
states. Better to just disable.


#+begin_src elisp
(setq compilation-save-buffers-predicate 'ignore)
#+end_src
* Org
** Keybinds
#+begin_src elisp
(global-set-key (kbd "C-c a") 'org-agenda)
#+end_src
** Agenda

#+begin_src elisp
(setq org-agenda-files '("~/Documents/roam"))
(setq org-agenda-file-regexp "\\`[^.].*\\.org\\\(\\.gpg\\\)?\\'")
#+end_src

** Information organization structures

#+begin_src elisp
(setq org-todo-keywords '((sequence "TODO(t)" "ACTIVE(a)" "WAITING(w)" "|" "DONE(d)" "CANCELED(c)" "DELIGATED(D)"))
      )
#+end_src

Dependencies should be enforced

#+begin_src elisp
(setq org-enforce-todo-dependencies t)
#+end_src

** Structure templating

#+begin_src elisp
(require 'org-tempo)
#+end_src

** Appearance of org buffers
*** Default starting visibility

#+begin_src elisp
(setq org-startup-indented t
      org-startup-folded t
      )
#+end_src

*** Removing visual noise of emphasis markers

We can make different emphasis markers more visually appealing by
rendering their effects directly and hiding their symbols. See below:

| raw             | rendered      |
|-----------------+---------------|
| =*BOLD*=          | *BOLD*          |
| =_UNDERLINE_=     | _UNDERLINE_     |
| =/ITALICS/=       | /ITALICS/       |
| =~code~=          | ~code~          |
| ==verbatim==      | =verbatim=      |
| =+strikethrough+= | +strikethrough+ |


#+begin_src elisp
(setq org-hide-emphasis-markers t)
#+end_src

*** Making font faces less harsh

I'm not the biggest fan of using =*= for headline markers and after
seeing it everywhere online, I'm convinced the majority is right by
using the =org-bullets= package.

#+begin_src elisp
(use-package org-bullets
  :ensure
  :config
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+end_src

Similarly, the displayed symbol for unordered lists can be
changed. This will change the appearance of =-= to =•=.

#+begin_src elisp
(font-lock-add-keywords 'org-mode
                        '(("^ *\\([-]\\) "
                           (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
#+end_src

** Babel

#+begin_src elisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((shell . t)))
#+end_src

#+begin_src elisp
(setq org-edit-src-content-indentation 0)
(setq org-src-preserve-indentation t)
#+end_src

* Generated files

#+begin_src elisp
(setq custom-file (locate-user-emacs-file "custom-vars.el"))
(setq make-backup-files nil)
(custom-set-variables
 '(auto-save-file-name-transforms `((".*"  ,(locate-user-emacs-file "autosaves/") t)))
 '(backup-directory-alist `((".*" . ,(locate-user-emacs-file "backups/")))))

(make-directory (locate-user-emacs-file "autosaves/") t)
#+end_src

